#!/usr/bin/env ruby
require 'json'
require 'fileutils'

slug = ARGV[0]

json_file = "./data/#{slug}.json"
data = JSON.parse(File.open(json_file).read)
base_path = "./source/images/#{slug}"
new_data = {
  name: data['name'],
  slug: data['slug'],
  tabs: []
}

data["sections"].each do |section|
  path = section['name'].downcase
  new_dir = File.join(base_path, path)
  FileUtils.mkdir_p(new_dir)
  section['items'].each do |file|
    old_path = File.join(base_path, file)
    new_path = File.join(new_dir, file)
    FileUtils.mv(old_path, new_path) if File.exist?(old_path)
  end

  new_data[:tabs].push(
    name: section['name'],
    path: path
  )
end

new_json = JSON.pretty_generate(new_data)
File.write(json_file, new_json)


