#!/usr/bin/env zsh
# Take all the js files in ./source/javascripts and output them directly in
# ./source for Middleman to pick them.

local tmpBuildDirectory=./sources

mkdir -p $tmpBuildDirectory
babel \
  ./source/javascripts/vendors/*.js \
  ./source/javascripts/*.js \
  --out-file $tmpBuildDirectory/all.js


